# This file is a template, and might need editing before it works

image: docker:dind

before_script:
  - echo "to login"
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN  u16-vbw2:4567
   
after_script:
  - echo "After script section"
  - echo "For example you might do some cleanup here"
   
build1:
  stage: build
  script:
    - echo "Do your build here"
    - docker build -t u16-vbw2:4567/root/citest .
    - docker push u16-vbw2:4567/root/citest
   
test1:
  stage: test
  script: 
    - echo "Do a test here"
   
test2:
  stage: test
  script: 
    - echo "Do another parallel test here"

deploy1:
  stage: deploy
  script:
    - echo "Do your deploy here"
    - docker service update --image $(docker inspect --type image --format '{{index .RepoDigests 0}}' u16-vbw2:4567/root/citest:latest) rosdisplay 
